In [76]:
import pandas as pd 
import time

In [77]:
df = pd.read_csv("startup_funding.csv")

In [78]:
df.head(5)

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [79]:
#startups = sorted(df['Startup Name'].unique().tolist())

In [80]:
#Investors = df['Investors Name'].unique().tolist()

In [97]:
df.head()

,date,startup,Vertical,subvertical,city,investors,round,amount in usd
Sr No,,,,,,,,
1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0
2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394.0
3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860.0
4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000.0
5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000.0

In [82]:
df.drop(columns = ['Remarks'], inplace = True)

In [83]:
df.set_index('Sr No', inplace = True)

In [84]:
df.rename(columns = {
    'Sr  No':'sr no',
    'Date dd/mm/yyyy': 'date',
    'Startup Name': 'startup',
    'Industry Vertical':'Vertical',
    'SubVertical':'subvertical',
    'City  Location':'city ',
    'Investors Name':'investors',
    'InvestmentnType': 'round',
    'Amount in USD': 'amount in usd'
}, inplace = True)

## changing amount to float

In [85]:
df1 = df

In [86]:
df1['amount in usd'] = df1['amount in usd'].str.replace(',','')
df1['amount in usd'] = df1['amount in usd'].str.replace('undisclosed','0')
df1['amount in usd'] = df1['amount in usd'].str.replace('unknown','0')
df1['amount in usd'] = df1['amount in usd'].str.replace('Undisclosed','0')

In [87]:
df1['amount in usd'] = df1['amount in usd'].fillna(0)

In [88]:
df1['amount in usd'] = pd.to_numeric(
    df1['amount in usd'],
    errors='coerce'
)

In [89]:
df['amount in usd']= df1['amount in usd'].astype('float')

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3044 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           3044 non-null   object
 1   startup        3044 non-null   object
 2   Vertical       2873 non-null   object
 3   subvertical    2108 non-null   object
 4   city           2864 non-null   object
 5   investors      3020 non-null   object
 6   round          3040 non-null   object
 7   amount in usd  3032 non-null   float64
dtypes: float64(1), object(7)
memory usage: 214.0+ KB

## Changing date to DateTime

In [90]:
df1["date"] = pd.to_datetime(
    df1["date"],
    format="%d/%m/%Y",  errors='coerce'
)

In [91]:
df["date"]= df1["date"]

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3044 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           3036 non-null   datetime64[ns]
 1   startup        3044 non-null   object
 2   Vertical       2873 non-null   object
 3   subvertical    2108 non-null   object
 4   city           2864 non-null   object
 5   investors      3020 non-null   object
 6   round          3040 non-null   object
 7   amount in usd  3032 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 214.0+ KB

## droping null values as much possible

In [102]:
df = df.dropna(subset=['date','startup','Vertical','investors','city ','round','amount in usd'] )

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2819 entries, 1 to 2873
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           2819 non-null   datetime64[ns]
 1   startup        2819 non-null   object
 2   Vertical       2819 non-null   object
 3   subvertical    2078 non-null   object
 4   city           2819 non-null   object
 5   investors      2819 non-null   object
 6   round          2819 non-null   object
 7   amount in usd  2819 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 198.2+ KB

In [104]:
df.to_csv("startup_cleaned_data.csv", index = False)

In [106]:
df.columns

Index(['date', 'startup', 'Vertical', 'subvertical', 'city ', 'investors',
       'round', 'amount in usd'],
      dtype='object')

In [111]:
Investors = sorted(set(df['investors'].str.split(',').sum()))

# Analysis 
## Investors

## Recent Investments

In [112]:
df2 = df

In [129]:
df2[df2['investors'].str.contains(' IDG Ventures')].groupby('startup')['amount in usd'].sum().sort_values(ascending = False)

startup
Lenskart                 60000000.0
CureFit                  25000000.0
Bizongo                  22000000.0
Curefit                  15000000.0
Xpressbees               12500000.0
FirstCry.com             10000000.0
POPxo                     8600000.0
\\xc2\\xa0CloudCherry     6000000.0
Sigtuple                  5800000.0
RentMojo                  5000000.0
Aasaanjobs                5000000.0
PlaySimple                4000000.0
Tripoto                   3591375.0
Active.ai                 3000000.0
Heckyl                    2700000.0
Little Black Book         1000000.0
Cloudcherry Analytics     1000000.0
Name: amount in usd, dtype: float64

In [130]:
df2[df2['investors'].str.contains(' IDG Ventures')].groupby('Vertical')['amount in usd'].sum().sort_values(ascending = False)

Vertical
Consumer Internet                  76100000.0
eCommerce                          70000000.0
Technology                         27000000.0
ECommerce                          12500000.0
Social Media                        3591375.0
CRM / Analytics platform            1000000.0
global community for travellers           0.0
Name: amount in usd, dtype: float64

In [131]:
df.head()

,date,startup,Vertical,subvertical,city,investors,round,amount in usd
Sr No,,,,,,,,
1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0
2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394.0
3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860.0
4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000.0
5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000.0

In [135]:
df['year']= df['date'].dt.year

/var/folders/xb/zx9yj1sx5593dy5vqr4rcs3c0000gn/T/ipykernel_35172/1677965158.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year']= df['date'].dt.year

In [136]:
df.head()

,date,startup,Vertical,subvertical,city,investors,round,amount in usd,year
Sr No,,,,,,,,,
1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0,2020
2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394.0,2020
3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860.0,2020
4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000.0,2020
5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000.0,2020

In [137]:
df2[df2['investors'].str.contains(' IDG Ventures')].groupby('year')['amount in usd'].sum()

year
2015     11000000.0
2016    110500000.0
2017     37600000.0
2018     27500000.0
2019      3591375.0
Name: amount in usd, dtype: float64

## Genral analysis

# 1. cards total+max+Avg+Total Starup

In [138]:
df.head()

,date,startup,Vertical,subvertical,city,investors,round,amount in usd,year
Sr No,,,,,,,,,
1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0,2020
2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394.0,2020
3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860.0,2020
4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000.0,2020
5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000.0,2020

In [144]:
print(f"${round(df['amount in usd'].sum())} ")

$35944759035

In [150]:
total = "$" + str(round(df['amount in usd'].sum()))
print(total)

$35944759035

Most money picked

In [155]:
df.groupby('startup')['amount in usd'].max().head(1)

startup
"BYJU\\'S"    150000000.0
Name: amount in usd, dtype: float64

In [157]:
df.groupby('startup')['amount in usd'].max().sort_values(ascending = False).head(1).values[0]

np.float64(3900000000.0)

In [166]:
df.groupby('startup')['amount in usd'].count().sum()

np.int64(2819)

In [172]:
df['month']= df['date'].dt.month

/var/folders/xb/zx9yj1sx5593dy5vqr4rcs3c0000gn/T/ipykernel_35172/2496768855.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month']= df['date'].dt.month

In [175]:
df

,date,startup,Vertical,subvertical,city,investors,round,amount in usd,year,month
Sr No,,,,,,,,,,
1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0,2020,1
2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394.0,2020,1
3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860.0,2020,1
4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000.0,2020,1
5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000.0,2020,1
...,...,...,...,...,...,...,...,...,...,...
2869,2015-04-29,Tracxn,Startup Analytics platform,NaN,Bangalore,SAIF Partners,Private Equity,3500000.0,2015,4
2870,2015-04-29,Dazo,Mobile Food Ordering app,NaN,Bangalore,"Sumit Jain, Aprameya Radhakrishna, Alok Goel, ...",Seed Funding,0.0,2015,4
2871,2015-04-29,Tradelab,Financial Markets Software,NaN,Bangalore,Rainmatter,Seed Funding,400000.0,2015,4
2872,2015-04-29,PiQube,Hiring Analytics platform,NaN,Chennai,The HR Fund,Seed Funding,500000.0,2015,4
2873,2015-04-29,Travel Triangle,Online Travel Marketplace,NaN,Noida,"Bessemer Venture Partners, SAIF Partners",Private Equity,8000000.0,2015,4

In [201]:
temp_df = df.groupby(['year','month'])['amount in usd'].count().reset_index()
temp_df['x-axis'] = temp_df['month'].astype('str')+"-"+temp_df["year"].astype('str')
temp_df[['amount in usd','x-axis']]

In [202]:
temp_df.head()

   year  month  amount in usd
0  2015      4             61
1  2015      5             55
2  2015      6             84
3  2015      7             85
4  2015      8             98

In [203]:
temp_df['x-axis'] = temp_df['month'].astype('str')+"-"+temp_df["year"].astype('str')

In [204]:
temp_df[['amount in usd','x-axis']]

    amount in usd   x-axis
0              61   4-2015
1              55   5-2015
2              84   6-2015
3              85   7-2015
4              98   8-2015
5              87   9-2015
6              93  10-2015
7              90  11-2015
8              88  12-2015
9             104   1-2016
10             99   2-2016
11             84   3-2016
12             77   4-2016
13             79   5-2016
14             97   6-2016
15             63   7-2016
16             87   8-2016
17             73   9-2016
18             80  10-2016
19             72  11-2016
20             72  12-2016
21             72   1-2017
22             48   2-2017
23             71   3-2017
24             71   4-2017
25             67   5-2017
26             65   6-2017
27             42   7-2017
28             45   8-2017
29             58   9-2017
30             53  10-2017
31             50  11-2017
32             42  12-2017
33             36   1-2018
34             42   2-2018
35             33   3-2018
36             32   4-2018
37             22   5-2018
38             32   6-2018
39             33   7-2018
40             21   8-2018
41             12   9-2018
42              7  10-2018
43             18  11-2018
44              7  12-2018
45              3   1-2019
46              3   2-2019
47             13   4-2019
48              9   5-2019
49             13   6-2019
50             13   7-2019
51             16   8-2019
52              9   9-2019
53              3  10-2019
54             14  11-2019
55              9  12-2019
56              7   1-2020